CREATE TABLE [dbo].[Logement]
(
	[id_Logement] INT IDENTITY (1,1) NOT NULL, 
    [nom] NVARCHAR(32) NOT NULL, 
    [adresseRue] NVARCHAR(256) NOT NULL, 
    [adresseNumero] NVARCHAR(16) NOT NULL, 
    [adresseCodePostal] NVARCHAR(16) NOT NULL, 
    [adressePays] NVARCHAR(16) NOT NULL, 
    [latitude] DECIMAL(10,7) NOT NULL, 
    [longitude] DECIMAL(10,7) NOT NULL, 
    [descCourte] NVARCHAR(255) NOT NULL, 
    [descLongue] NVARCHAR(MAX) NOT NULL, 
    [nbChambre] TINYINT NOT NULL, 
    [nbPiece] TINYINT NOT NULL DEFAULT 1,  
    [nbPersonne] TINYINT NOT NULL DEFAULT 1, 
    [nbDouche] TINYINT NOT NULL DEFAULT 1, 
    [nbWC] TINYINT NOT NULL DEFAULT 1, 
    [balcon] BIT NOT NULL DEFAULT 0 , 
    [airCo] BIT NOT NULL DEFAULT 0, 
    [wifi] BIT NOT NULL DEFAULT 1, 
    [miniBar] BIT NOT NULL DEFAULT 0, 
    [animaux] BIT NOT NULL DEFAULT 1, 
    [piscine] BIT NOT NULL DEFAULT 0, 
    [voiturier] BIT NOT NULL DEFAULT 0, 
    [roomService] BIT NOT NULL DEFAULT 0, 
    [prix] MONEY NOT NULL,
    [dateCreation] DATETIME NOT NULL DEFAULT GETDATE(),
    [id_Proprietaire] INT NOT NULL,
    [id_TypeLogement] INT NOT NULL,  
    CONSTRAINT [PK_id_Logement] PRIMARY KEY CLUSTERED ([id_Logement] ASC),
    CONSTRAINT FK_Logement_Client FOREIGN KEY ([id_Proprietaire]) REFERENCES [Proprietaire] (id_Client),
    CONSTRAINT FK_Logement_TypeLogement FOREIGN KEY (id_TypeLogement) REFERENCES TypeLogement (id_TypeLogement)
)

